/**
 * Conversation Schema
 * 
 * Defines the structure for storing AI chat conversations
 * for the Hub Sales Assistant.
 */

import { ObjectId } from 'mongodb';

/**
 * A single message in a conversation
 */
export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  /** Attachment IDs referenced in this message (for user messages) */
  attachmentIds?: string[];
}

/**
 * A file attachment uploaded by the user
 */
export interface ConversationAttachment {
  id: string;
  filename: string;
  mimeType: string;
  s3Key: string;
  size: number;
  uploadedAt: Date;
  /** Extracted text content for documents (PDF, CSV, TXT, MD, Excel) */
  extractedText?: string;
  /** Flag for image files that should use Claude vision */
  isImage?: boolean;
}

/**
 * A file generated by the assistant (proposals, packages)
 */
export interface GeneratedFile {
  id: string;
  filename: string;
  fileType: 'proposal_md' | 'package_csv';
  s3Key: string;
  createdAt: Date;
  /** Message index where this file was generated */
  messageIndex?: number;
}

/**
 * Conversation context - tracks brand/campaign info across messages
 */
export interface ConversationContext {
  brandName?: string;
  brandUrl?: string;
  budgetMonthly?: number;
  budgetTotal?: number;
  campaignDuration?: string;
  targetAudience?: string;
  geographicFocus?: string;
  objectives?: string[];
  /** Any additional context the assistant wants to track */
  notes?: string;
}

/**
 * Cumulative token usage for a conversation
 */
export interface ConversationTokenUsage {
  totalInputTokens: number;
  totalOutputTokens: number;
  /** Number of AI exchanges (user message + assistant response pairs) */
  exchangeCount: number;
}

/**
 * Main conversation document
 */
export interface Conversation {
  _id?: string | ObjectId;
  conversationId: string; // Unique identifier
  userId: string; // Owner of the conversation
  hubId: string; // Associated hub (for filtering)
  title: string; // Auto-generated or user-set title
  messages: ConversationMessage[]; // Chat history
  
  /** User-uploaded file attachments */
  attachments?: ConversationAttachment[];
  
  /** Files generated by the assistant (proposals, packages) */
  generatedFiles?: GeneratedFile[];
  
  /** Brand/campaign context tracked across the conversation */
  context?: ConversationContext;
  
  /** Cumulative token usage across all messages */
  tokenUsage?: ConversationTokenUsage;
  
  /** @deprecated Use attachments instead */
  contextFiles?: {
    fileId?: string;
    uploadedAt?: Date;
    publicationCount?: number;
  };
  
  metadata: {
    createdAt: Date;
    updatedAt: Date;
    messageCount: number;
    lastMessageAt?: Date;
  };
}

export interface ConversationInsert extends Omit<Conversation, '_id'> {}

// Collection name
export const CONVERSATION_COLLECTION = 'conversations';

// File upload limits
export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
export const MAX_FILES_PER_CONVERSATION = 10;

// Supported file types for upload
export const SUPPORTED_UPLOAD_TYPES = {
  documents: [
    'application/pdf',
    'text/plain',
    'text/html',
    'text/markdown',
    'text/csv',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ],
  images: [
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/webp',
  ],
} as const;

export const ALL_SUPPORTED_TYPES = [
  ...SUPPORTED_UPLOAD_TYPES.documents,
  ...SUPPORTED_UPLOAD_TYPES.images,
];

