-- Phase 1: Enhance ad_packages table schema
ALTER TABLE public.ad_packages 
ADD COLUMN tagline text,
ADD COLUMN price text,
ADD COLUMN audience text[],
ADD COLUMN channels text[],
ADD COLUMN complexity text,
ADD COLUMN outlets text[];

-- Phase 2: Insert all package data from static data
INSERT INTO public.ad_packages (
  legacy_id, name, tagline, description, price, price_range, audience, channels, complexity, outlets, features, is_active
) VALUES 
  (1, 'Local Business Spotlight', 'Showcase your business to local customers', 'Perfect for small businesses looking to increase local awareness and foot traffic. This package includes strategic placement across our most popular local media channels.', '$2,500', 'budget', ARRAY['local-residents', 'families'], ARRAY['print', 'digital'], 'turnkey', ARRAY['Chicago Tribune Local', 'ABC 7 Chicago', 'Chicago Sun-Times'], '["Professional photography session", "Custom ad design", "Social media boost", "Performance analytics"]'::jsonb, true),
  
  (2, 'Digital Marketing Boost', 'Amplify your online presence', 'Comprehensive digital marketing package designed to increase your online visibility and drive website traffic through targeted digital campaigns.', '$3,800', 'mid-range', ARRAY['professionals', 'millennials'], ARRAY['digital', 'social'], 'turnkey', ARRAY['Chicago Tribune Digital', 'Block Club Chicago', 'Chicagoist'], '["SEO optimization", "Google Ads management", "Social media campaign", "Email marketing", "Analytics dashboard"]'::jsonb, true),

  (3, 'Premium Brand Campaign', 'Elevate your brand to new heights', 'High-impact multimedia campaign perfect for established businesses ready to make a significant market impression with premium placements.', '$8,500', 'premium', ARRAY['affluent', 'professionals'], ARRAY['tv', 'print', 'digital'], 'custom', ARRAY['WGN-TV', 'Chicago Magazine', 'Crain''s Chicago Business'], '["TV commercial production", "Print ad design", "Digital banner ads", "Influencer partnerships", "Dedicated account manager"]'::jsonb, true),

  (4, 'Startup Launch Package', 'Perfect introduction for new businesses', 'Designed specifically for startups and new businesses entering the Chicago market. Cost-effective way to build initial brand awareness.', '$1,800', 'budget', ARRAY['entrepreneurs', 'young-professionals'], ARRAY['digital', 'social'], 'turnkey', ARRAY['Block Club Chicago', 'Chicago Startup News', 'Built In Chicago'], '["Logo placement", "Sponsored content", "Social media mentions", "Press release distribution"]'::jsonb, true),

  (5, 'Healthcare Professional Focus', 'Reach patients and healthcare networks', 'Specialized package for healthcare providers, medical practices, and health-related businesses targeting patients and medical professionals.', '$4,200', 'mid-range', ARRAY['patients', 'healthcare-professionals'], ARRAY['print', 'digital', 'health'], 'turnkey', ARRAY['Chicago Tribune Health', 'Modern Healthcare', 'Chicago Medical Society Publications'], '["Patient education materials", "Professional network outreach", "Health blog features", "Medical conference presence"]'::jsonb, true),

  (6, 'Restaurant & Food Service', 'Appetite-appealing marketing for food businesses', 'Mouth-watering marketing package for restaurants, catering services, and food-related businesses to attract hungry customers.', '$3,200', 'mid-range', ARRAY['food-enthusiasts', 'local-residents'], ARRAY['social', 'digital', 'lifestyle'], 'turnkey', ARRAY['Chicago Eater', 'Time Out Chicago', 'Chicago Food Magazine'], '["Food photography", "Menu design", "Social media campaigns", "Food blogger outreach", "Event promotion"]'::jsonb, true),

  (7, 'Tech Company Showcase', 'Innovation-focused marketing for tech businesses', 'Cutting-edge marketing approach for technology companies, startups, and digital service providers in the Chicago tech scene.', '$5,500', 'mid-range', ARRAY['tech-professionals', 'entrepreneurs'], ARRAY['digital', 'tech', 'social'], 'custom', ARRAY['Built In Chicago', 'Chicago Inno', 'TechCrunch Chicago'], '["Product demo videos", "Thought leadership content", "Tech conference sponsorship", "Developer community outreach"]'::jsonb, true),

  (8, 'Real Estate Professional', 'Property marketing that sells', 'Comprehensive marketing solution for real estate agents, brokers, and property developers to showcase listings and build client trust.', '$4,800', 'mid-range', ARRAY['home-buyers', 'investors'], ARRAY['print', 'digital', 'real-estate'], 'turnkey', ARRAY['Chicago Real Estate Daily', 'Curbed Chicago', 'Chicago Agent Magazine'], '["Property photography", "Virtual tour creation", "Market analysis graphics", "Client testimonial videos"]'::jsonb, true),

  (9, 'Educational Institution', 'Academic excellence marketing', 'Tailored for schools, universities, and educational service providers to attract students, parents, and academic partnerships.', '$6,200', 'premium', ARRAY['students', 'parents', 'educators'], ARRAY['print', 'digital', 'education'], 'custom', ARRAY['Chicago Tribune Education', 'University of Chicago Publications', 'Chicago Public Media'], '["Campus showcase videos", "Student success stories", "Academic achievement highlights", "Parent information sessions"]'::jsonb, true),

  (10, 'Luxury Brand Experience', 'Exclusive marketing for premium brands', 'Ultra-premium package for luxury brands and high-end service providers targeting affluent Chicago consumers.', '$12,000', 'premium', ARRAY['affluent', 'luxury-consumers'], ARRAY['print', 'tv', 'luxury'], 'custom', ARRAY['Chicago Magazine', 'Michigan Avenue Magazine', 'WGN-TV'], '["Luxury brand photoshoot", "Exclusive event marketing", "VIP customer outreach", "Premium publication features"]'::jsonb, true),

  (11, 'Non-Profit Awareness', 'Mission-driven marketing for good causes', 'Purpose-built package for non-profit organizations, charities, and community groups to raise awareness and drive engagement.', '$2,200', 'budget', ARRAY['community-members', 'volunteers'], ARRAY['social', 'community', 'digital'], 'turnkey', ARRAY['Chicago Tribune Community', 'Block Club Chicago', 'Chicago Volunteer Network'], '["Cause awareness campaigns", "Volunteer recruitment", "Donation drive promotion", "Community event coverage"]'::jsonb, true),

  (12, 'Financial Services Focus', 'Trust-building marketing for financial professionals', 'Specialized package for financial advisors, insurance agents, and financial service providers to build credibility and attract clients.', '$5,200', 'mid-range', ARRAY['investors', 'professionals'], ARRAY['print', 'digital', 'financial'], 'turnkey', ARRAY['Crain''s Chicago Business', 'Chicago Business Journal', 'Financial Planning Magazine'], '["Financial expertise showcasing", "Client success stories", "Market analysis content", "Professional headshots"]'::jsonb, true),

  (13, 'Legal Professional', 'Authority-building for legal services', 'Comprehensive marketing for law firms and legal professionals to establish thought leadership and attract quality clients.', '$6,800', 'premium', ARRAY['business-owners', 'individuals-needing-legal-help'], ARRAY['print', 'digital', 'legal'], 'custom', ARRAY['Chicago Lawyer Magazine', 'Crain''s Chicago Business', 'Chicago Bar Association Publications'], '["Legal expertise articles", "Case study presentations", "Professional photography", "Speaking engagement promotion"]'::jsonb, true),

  (14, 'Fashion & Beauty', 'Style-conscious marketing for beauty brands', 'Trendsetting package for fashion retailers, beauty salons, and lifestyle brands targeting style-conscious Chicago consumers.', '$4,500', 'mid-range', ARRAY['fashion-conscious', 'beauty-enthusiasts'], ARRAY['social', 'lifestyle', 'digital'], 'turnkey', ARRAY['Chicago Magazine Style', 'Fashion Chicago', 'Beauty Chicago'], '["Fashion photography", "Style guide creation", "Influencer collaborations", "Trend analysis content"]'::jsonb, true),

  (15, 'Fitness & Wellness', 'Health-focused marketing for wellness businesses', 'Energizing package for gyms, wellness centers, and health coaches to motivate and attract health-conscious consumers.', '$3,600', 'mid-range', ARRAY['health-conscious', 'fitness-enthusiasts'], ARRAY['social', 'digital', 'health'], 'turnkey', ARRAY['Chicago Health & Fitness', 'Well+Good Chicago', 'Chicago Runner'], '["Workout video content", "Health tip graphics", "Success story features", "Wellness event promotion"]'::jsonb, true),

  (16, 'Entertainment & Events', 'Show-stopping marketing for entertainment', 'Dynamic package for entertainment venues, event planners, and performance artists to create buzz and sell tickets.', '$5,800', 'mid-range', ARRAY['entertainment-seekers', 'event-goers'], ARRAY['social', 'digital', 'entertainment'], 'custom', ARRAY['Time Out Chicago', 'Chicago Reader', 'Chicago Entertainment Weekly'], '["Event photography", "Video trailers", "Social media buzz", "Influencer partnerships", "Ticket promotion"]'::jsonb, true),

  (17, 'Automotive Excellence', 'Drive sales with automotive marketing', 'High-octane package for car dealerships, auto service centers, and automotive businesses to accelerate customer acquisition.', '$4,400', 'mid-range', ARRAY['car-buyers', 'auto-enthusiasts'], ARRAY['digital', 'print', 'automotive'], 'turnkey', ARRAY['Chicago Auto Show Publications', 'AutoTrader Chicago', 'Chicago Motors Magazine'], '["Vehicle photography", "Test drive promotions", "Service specials", "Customer testimonials"]'::jsonb, true),

  (18, 'Home & Garden', 'Beautiful marketing for home improvement', 'Inspiring package for home improvement contractors, landscapers, and interior designers to showcase their transformative work.', '$3,800', 'mid-range', ARRAY['homeowners', 'home-improvement-enthusiasts'], ARRAY['print', 'digital', 'home'], 'turnkey', ARRAY['Chicago Home & Garden', 'Better Homes Chicago', 'HGTV Chicago'], '["Before/after photography", "Design showcase videos", "Home improvement tips", "Seasonal promotions"]'::jsonb, true),

  (19, 'Pet Services & Care', 'Paw-some marketing for pet businesses', 'Adorable package for veterinarians, pet stores, and pet service providers to connect with Chicago''s pet-loving community.', '$2,800', 'budget', ARRAY['pet-owners', 'animal-lovers'], ARRAY['social', 'digital', 'community'], 'turnkey', ARRAY['Chicago Pet Magazine', 'Windy City Pets', 'Chicago Animal Care Network'], '["Pet photography", "Care tip content", "Pet owner testimonials", "Adoption event promotion"]'::jsonb, true),

  (20, 'Senior Living Services', 'Compassionate marketing for senior care', 'Caring package for senior living facilities, healthcare providers, and services targeting seniors and their families.', '$4,600', 'mid-range', ARRAY['seniors', 'adult-children-of-seniors'], ARRAY['print', 'digital', 'healthcare'], 'turnkey', ARRAY['Chicago Senior Living Guide', 'AARP Chicago', 'Senior Planet'], '["Facility showcase tours", "Resident testimonials", "Care quality highlights", "Family education materials"]'::jsonb, true),

  (21, 'Environmental & Green', 'Sustainable marketing for eco-conscious brands', 'Earth-friendly package for environmental organizations, green businesses, and sustainability-focused companies.', '$3,400', 'mid-range', ARRAY['environmentally-conscious', 'sustainability-advocates'], ARRAY['digital', 'community', 'environmental'], 'turnkey', ARRAY['Chicago Green Business Network', 'Sustainable Chicago', 'EcoChicago'], '["Sustainability showcases", "Environmental impact stories", "Green certification highlights", "Eco-event promotion"]'::jsonb, true),

  (22, 'Cultural & Arts', 'Creative marketing for cultural organizations', 'Artistic package for museums, galleries, theaters, and cultural institutions to promote events and engage art enthusiasts.', '$5,400', 'mid-range', ARRAY['arts-enthusiasts', 'culture-seekers'], ARRAY['social', 'digital', 'cultural'], 'custom', ARRAY['Chicago Cultural Center Publications', 'Art Chicago Magazine', 'Chicago Arts Network'], '["Exhibition photography", "Artist interviews", "Cultural event promotion", "Art education content"]'::jsonb, true),

  (23, 'Professional Services', 'Expert marketing for service professionals', 'Versatile package for consultants, accountants, and professional service providers to demonstrate expertise and attract clients.', '$4,200', 'mid-range', ARRAY['business-owners', 'professionals'], ARRAY['print', 'digital', 'professional'], 'turnkey', ARRAY['Chicago Business Journal', 'Professional Services Chicago', 'Crain''s Chicago Business'], '["Expertise demonstrations", "Client case studies", "Professional photography", "Industry thought leadership"]'::jsonb, true),

  (24, 'Enterprise Solution', 'Comprehensive marketing for large businesses', 'Full-scale marketing solution for large enterprises and corporations requiring comprehensive multi-channel campaigns.', '$15,000', 'premium', ARRAY['enterprise-clients', 'b2b-decision-makers'], ARRAY['tv', 'print', 'digital', 'enterprise'], 'custom', ARRAY['WGN-TV', 'Chicago Tribune', 'Crain''s Chicago Business', 'Chicago Magazine'], '["Multi-channel campaign", "Executive photography", "Corporate video production", "Industry conference presence", "Dedicated marketing team"]'::jsonb, true);