// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnvbzjcsgyctmbvftlii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudmJ6amNzZ3ljdG1idmZ0bGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjQwNjIsImV4cCI6MjA3MzcwMDA2Mn0.Fg4ZH1o3jwjKOR8JSwwI4Ac68TtTMKjXlZRgOouza2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});